services:
  # PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 6000:8080